/* ════════════════════════════════════════════
   js/data.js — Indian Influencer & Brand Data
   All influencers: Indian, followers 5K–18K
   All budgets in USD
   ════════════════════════════════════════════ */

export const INFLUENCERS = [
  {
    id: 1,
    name: 'Arjun Mehta',
    handle: '@arjunmehta',
    platform: 'Instagram',
    niche: 'Lifestyle',
    followers: '12.4K',
    engRate: '8.7%',
    rate: '$85',
    bio: 'Mumbai-based lifestyle creator sharing minimalist living, productivity and city culture with an engaged community.',
    initials: 'AM',
    gradient: 'linear-gradient(135deg,#f093fb,#f5576c)',
    badge: 'badge-ig',
    location: 'Mumbai'
  },
  {
    id: 2,
    name: 'Priya Sharma',
    handle: '@priya.creates',
    platform: 'Instagram',
    niche: 'Fashion',
    followers: '9.8K',
    engRate: '11.2%',
    rate: '$65',
    bio: 'Delhi fashion blogger styling affordable Indian streetwear and fusion looks for everyday women.',
    initials: 'PS',
    gradient: 'linear-gradient(135deg,#fccb90,#d57eeb)',
    badge: 'badge-ig',
    location: 'Delhi'
  },
  {
    id: 3,
    name: 'Rohan Verma',
    handle: '@rohantech.in',
    platform: 'YouTube',
    niche: 'Tech & Gadgets',
    followers: '16.1K',
    engRate: '6.4%',
    rate: '$120',
    bio: 'Bengaluru tech reviewer breaking down smartphones, laptops and Indian startups in simple Hindi and English.',
    initials: 'RV',
    gradient: 'linear-gradient(135deg,#4facfe,#00f2fe)',
    badge: 'badge-yt',
    location: 'Bengaluru'
  },
  {
    id: 4,
    name: 'Sneha Kapoor',
    handle: '@snehabeauty',
    platform: 'Instagram',
    niche: 'Beauty & Skincare',
    followers: '14.5K',
    engRate: '9.3%',
    rate: '$95',
    bio: 'Chandigarh-based beauty creator reviewing Indian skincare brands and sharing honest dupes for high-end products.',
    initials: 'SK',
    gradient: 'linear-gradient(135deg,#ee0979,#ff6a00)',
    badge: 'badge-ig',
    location: 'Chandigarh'
  },
  {
    id: 5,
    name: 'Vikram Nair',
    handle: '@vikramfitness',
    platform: 'Instagram',
    niche: 'Fitness & Health',
    followers: '11.3K',
    engRate: '10.8%',
    rate: '$75',
    bio: 'Kochi-based certified trainer helping 11K followers build strength at home with zero-equipment workouts.',
    initials: 'VN',
    gradient: 'linear-gradient(135deg,#11998e,#38ef7d)',
    badge: 'badge-ig',
    location: 'Kochi'
  },
  {
    id: 6,
    name: 'Ananya Iyer',
    handle: '@ananyas.kitchen',
    platform: 'YouTube',
    niche: 'Food & Cooking',
    followers: '13.7K',
    engRate: '7.9%',
    rate: '$90',
    bio: 'Chennai home chef sharing South Indian recipes, fusion cooking and quick 20-minute meal ideas for families.',
    initials: 'AI',
    gradient: 'linear-gradient(135deg,#f7971e,#ffd200)',
    badge: 'badge-yt',
    location: 'Chennai'
  },
  {
    id: 7,
    name: 'Kabir Singh',
    handle: '@kabir.games',
    platform: 'YouTube',
    niche: 'Gaming',
    followers: '17.8K',
    engRate: '5.9%',
    rate: '$110',
    bio: 'Hyderabad-based gaming creator covering BGMI, Valorant and mobile gaming reviews in entertaining formats.',
    initials: 'KS',
    gradient: 'linear-gradient(135deg,#8e2de2,#4a00e0)',
    badge: 'badge-yt',
    location: 'Hyderabad'
  },
  {
    id: 8,
    name: 'Divya Patel',
    handle: '@divya.explores',
    platform: 'Instagram',
    niche: 'Travel & Adventure',
    followers: '8.2K',
    engRate: '12.4%',
    rate: '$60',
    bio: 'Ahmedabad travel blogger exploring budget-friendly India destinations and weekend getaways from Tier-2 cities.',
    initials: 'DP',
    gradient: 'linear-gradient(135deg,#00b09b,#96c93d)',
    badge: 'badge-ig',
    location: 'Ahmedabad'
  },
  {
    id: 9,
    name: 'Rahul Gupta',
    handle: '@rahulfinance',
    platform: 'YouTube',
    niche: 'Finance & Business',
    followers: '15.4K',
    engRate: '6.8%',
    rate: '$100',
    bio: 'Jaipur-based finance educator simplifying stock markets, mutual funds and personal finance for young Indians.',
    initials: 'RG',
    gradient: 'linear-gradient(135deg,#2af598,#009efd)',
    badge: 'badge-yt',
    location: 'Jaipur'
  },
  {
    id: 10,
    name: 'Meera Krishnan',
    handle: '@meeracooks',
    platform: 'Instagram',
    niche: 'Food & Cooking',
    followers: '6.9K',
    engRate: '14.1%',
    rate: '$50',
    bio: 'Pune micro-creator with massive engagement — plant-based Indian recipes that your followers will actually cook.',
    initials: 'MK',
    gradient: 'linear-gradient(135deg,#fddb92,#d1fdff)',
    badge: 'badge-ig',
    location: 'Pune'
  },
  {
    id: 11,
    name: 'Aditya Joshi',
    handle: '@adityacreates',
    platform: 'Instagram',
    niche: 'Lifestyle',
    followers: '10.6K',
    engRate: '9.5%',
    rate: '$70',
    bio: 'Indore creator documenting student life, self-improvement habits and affordable city living in central India.',
    initials: 'AJ',
    gradient: 'linear-gradient(135deg,#a18cd1,#fbc2eb)',
    badge: 'badge-ig',
    location: 'Indore'
  },
  {
    id: 12,
    name: 'Pooja Reddy',
    handle: '@poojabeauty',
    platform: 'Instagram',
    niche: 'Beauty & Skincare',
    followers: '7.5K',
    engRate: '13.2%',
    rate: '$55',
    bio: 'Hyderabad beauty creator focused on South Indian skin tones, traditional remedies and cruelty-free products.',
    initials: 'PR',
    gradient: 'linear-gradient(135deg,#f78ca0,#f9748f)',
    badge: 'badge-ig',
    location: 'Hyderabad'
  },
];

export const BRANDS = [
  {
    id: 1,
    name: 'Mamaearth',
    niche: 'Beauty & Skincare',
    location: 'Gurugram, Haryana',
    budgetMin: 250,
    budgetMax: 900,
    needs: 'Skincare creators who can showcase toxin-free ingredients and honest skin-transformation results.',
    initials: 'ME',
    gradient: 'linear-gradient(135deg,#11998e,#38ef7d)',
  },
  {
    id: 2,
    name: 'boAt Lifestyle',
    niche: 'Tech',
    location: 'New Delhi',
    budgetMin: 400,
    budgetMax: 1500,
    needs: 'Tech & lifestyle influencers for audio, wearables and power product unboxings and reviews.',
    initials: 'BL',
    gradient: 'linear-gradient(135deg,#4facfe,#00f2fe)',
  },
  {
    id: 3,
    name: 'Lenskart',
    niche: 'Fashion',
    location: 'Gurugram, Haryana',
    budgetMin: 300,
    budgetMax: 1200,
    needs: 'Fashion creators for try-on hauls and eyewear styling content across Instagram Reels.',
    initials: 'LK',
    gradient: 'linear-gradient(135deg,#f7971e,#ffd200)',
  },
  {
    id: 4,
    name: 'Zomato',
    niche: 'Food & Beverage',
    location: 'Gurugram, Haryana',
    budgetMin: 200,
    budgetMax: 800,
    needs: 'Food bloggers and restaurant reviewers for city-specific content campaigns.',
    initials: 'ZO',
    gradient: 'linear-gradient(135deg,#ee0979,#ff6a00)',
  },
  {
    id: 5,
    name: 'Nykaa',
    niche: 'Beauty & Skincare',
    location: 'Mumbai, Maharashtra',
    budgetMin: 350,
    budgetMax: 1400,
    needs: 'Beauty creators for GRWM, tutorials and makeup product launches targeting urban Indian women.',
    initials: 'NY',
    gradient: 'linear-gradient(135deg,#f093fb,#f5576c)',
  },
  {
    id: 6,
    name: 'BYJU\'S',
    niche: 'Education',
    location: 'Bengaluru, Karnataka',
    budgetMin: 300,
    budgetMax: 1100,
    needs: 'Education-focused creators to promote online learning solutions for students and parents.',
    initials: 'BJ',
    gradient: 'linear-gradient(135deg,#2af598,#009efd)',
  },
  {
    id: 7,
    name: 'OYO Rooms',
    niche: 'Travel',
    location: 'Gurugram, Haryana',
    budgetMin: 250,
    budgetMax: 1000,
    needs: 'Travel content creators for staycation reviews, weekend getaway content and destination guides.',
    initials: 'OY',
    gradient: 'linear-gradient(135deg,#f7971e,#84fab0)',
  },
  {
    id: 8,
    name: 'PhonePe',
    niche: 'Finance',
    location: 'Bengaluru, Karnataka',
    budgetMin: 400,
    budgetMax: 1600,
    needs: 'Finance-savvy creators for UPI, investment and digital payment awareness campaigns across India.',
    initials: 'PP',
    gradient: 'linear-gradient(135deg,#6a3093,#a044ff)',
  },
  {
    id: 9,
    name: 'Wakefit',
    niche: 'Lifestyle',
    location: 'Bengaluru, Karnataka',
    budgetMin: 200,
    budgetMax: 750,
    needs: 'Home and lifestyle creators for sleep, wellness and home décor product integration campaigns.',
    initials: 'WF',
    gradient: 'linear-gradient(135deg,#a18cd1,#fbc2eb)',
  },
  {
    id: 10,
    name: 'Noise',
    niche: 'Tech',
    location: 'Gurugram, Haryana',
    budgetMin: 300,
    budgetMax: 1200,
    needs: 'Smartwatch and wearable reviewers for launch content, unboxings and fitness use-case videos.',
    initials: 'NO',
    gradient: 'linear-gradient(135deg,#00c6ff,#0072ff)',
  },
  {
    id: 11,
    name: 'The Whole Truth',
    niche: 'Food & Beverage',
    location: 'Mumbai, Maharashtra',
    budgetMin: 150,
    budgetMax: 600,
    needs: 'Health-conscious creators to promote clean-label protein bars and honest nutrition content.',
    initials: 'WT',
    gradient: 'linear-gradient(135deg,#fddb92,#d1fdff)',
  },
  {
    id: 12,
    name: 'Campus Sutra',
    niche: 'Fashion',
    location: 'Surat, Gujarat',
    budgetMin: 180,
    budgetMax: 700,
    needs: 'Youth fashion creators for college and casual wear campaigns targeting 18–28 age group.',
    initials: 'CS',
    gradient: 'linear-gradient(135deg,#ee9ca7,#ffdde1)',
  },
];
